# -*- coding: utf-8 -*-
"""EDA_DA-1_21BDS0148

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c_wY5k8yFRgdP96u9xfOc8bGQcTOl6Yk

EDA DA-1 21BDS0148
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
AmogVardhanKona = pd.read_csv('eda_data_21BDS0148.csv')

roll_number_last4_0148 = 148

# dataFrame 1: Fname - state, statecode, year
AmogVardhanKona1 = {
    'state': ['NY', 'FL', 'MI', 'TX', 'UT'],
    'statecode': [35, 10, 23, 44, 45],
    'year': [1967, 1967, 1967, 1967, 1967]
}
df1_0148 = pd.DataFrame(AmogVardhanKona1)

# dataFrame 2: Lname - consumption, price, eprice
AmogVardhanKona2 = {
    'consumption': [313656, 9430, 302472, 201407, 38935],
    'price': [1.42, 2.26, 0.98, 0.87, 0.68],
    'eprice': [2.98, 2.16, 2.32, 2.19, 2.25]
}
df2_0148 = pd.DataFrame(AmogVardhanKona2)

# Show both DataFrames
print("DataFrame 1 (Fname):")
print(df1_0148)

print("\nDataFrame 2 (Lname):")
print(df2_0148)

# 1. Append (rows): Append df2 to df1 using pd.concat()
df_append_0148 = pd.concat([df1_0148, df2_0148], ignore_index=True)
print("\nDataFrame after Appending df2 to df1 using pd.concat():")
print(df_append_0148)

# 2. Concatenate: Concatenate df1 and df2 by columns (aligning them side by side)
df_concat_0148 = pd.concat([df1_0148, df2_0148], axis=1)
print("\nDataFrame after Concatenating df1 and df2:")
print(df_concat_0148)

# 3. Merge: Merge df1 and df2 on index (since there's no common column)
df_merge_0148 = pd.merge(df1_0148, df2_0148, left_index=True, right_index=True)
print("\nDataFrame after Merging df1 and df2 on index:")
print(df_merge_0148)

# 4. Join: Join df1 and df2 on the index
df_join_0148 = df1_0148.join(df2_0148)
print("\nDataFrame after Joining df1 and df2 on the index:")
print(df_join_0148)

# Display the first few rows of the dataframe
print("Original DataFrame:")
print(AmogVardhanKona.head())

# Insert the first record
first_record_0148 = {
    'rownames': 0,
    'state': 'Amogh Vardhan Kona',
    'statecode': 148,
    'year': 148,
    'consumption': 148,
    'price': 148,
    'eprice': 148,
    'oprice': np.nan,
    'lprice': np.nan,
    'heating': np.nan,
    'income': np.nan
}

# Convert the first record to a DataFrame and concatenate it with the existing DataFrame
first_record_df_0148 = pd.DataFrame([first_record_0148])
AmogVardhanKona = pd.concat([first_record_df_0148, AmogVardhanKona], ignore_index=True)

# Display the updated dataframe
print("\nUpdated DataFrame with First Record:")
print(AmogVardhanKona.head())

# Check if there exists any NA (missing values) in the dataset
any_na_0148 = AmogVardhanKona.isna().any().any()
print(f"\nDoes the dataset contain any missing values? {any_na_0148}")

# Finding the missing summaries of the dataset (summary of missing values per column)
missing_summary_0148 = AmogVardhanKona.isna().sum()
print("\nMissing Values Summary (per column):")
print(missing_summary_0148)

# Find the total number of NA (missing values) in the dataset
total_na_0148 = AmogVardhanKona.isna().sum().sum()
print(f"\nTotal number of missing values in the dataset: {total_na_0148}")

# Count the total number of complete cases in oprice and lprice
complete_cases_0148 = AmogVardhanKona[['oprice', 'lprice']].notna().all(axis=1).sum()
print(f"\nTotal number of complete cases in oprice and lprice: {complete_cases_0148}")

# Proportion of missing and complete data
prop_missing_0148 = AmogVardhanKona.isna().mean()
prop_complete_0148 = 1 - prop_missing_0148
print("\nProportion of Missing Values per Column:")
print(prop_missing_0148)
print("\nProportion of Complete Values per Column:")
print(prop_complete_0148)

# Display the missing values per column for each observation
# Create a missing data heatmap
plt.figure(figsize=(10, 6))
sns.heatmap(AmogVardhanKona.isna(), cbar=False, cmap='viridis')
plt.title("21BDS0148 - Missing Data Heatmap")
plt.show()

# Performing row-wise deletion (drop rows with any missing values)
AmogVardhanKona_cleaned_0148 = AmogVardhanKona.dropna()

# Display the cleaned dataframe
print("\nDataFrame after Row-wise Deletion (NaN Rows Removed):")
print(AmogVardhanKona_cleaned_0148.head())

# Check the number of rows before and after row deletion
print(f"\nNumber of rows before deletion: {len(AmogVardhanKona)}")
print(f"Number of rows after deletion: {len(AmogVardhanKona_cleaned_0148)}")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Step 1: Load the Dataset
AmogVardhanKona = pd.read_csv("eda_data_21BDS0148.csv")

# Step 2: Convert all column names to lowercase
AmogVardhanKona.columns = AmogVardhanKona.columns.str.lower()

# Step 3: Replace '?' with NaN for all columns
AmogVardhanKona.replace('?', np.nan, inplace=True)

# Step 4: Display the number of rows and columns in the dataset
print("Dimensions of the dataset:", AmogVardhanKona.shape)

# Step 5: Display the header or attribute names from the dataset
print("Column names:", AmogVardhanKona.columns)

# Step 6: Display the structure of the dataset (info)
print("Structure of the dataset:")
AmogVardhanKona.info()

# Step 7: View the first 3 and last 3 rows of the dataset
print("First 3 rows of the dataset:")
print(AmogVardhanKona.head(3))

print("Last 3 rows of the dataset:")
print(AmogVardhanKona.tail(3))

# Step 9: Displaying Summary Statistics
print("Summary Statistics of the dataset:")
print(AmogVardhanKona.describe())

# Step 10: Data Cleaning

# 10.1 Find out the number of values that are not numeric in 'price', 'consumption', and 'eprice'
non_numeric_price_0148 = AmogVardhanKona['price'].apply(pd.to_numeric, errors='coerce').isna().sum()
non_numeric_consumption_0148 = AmogVardhanKona['consumption'].apply(pd.to_numeric, errors='coerce').isna().sum()
non_numeric_eprice_0148 = AmogVardhanKona['eprice'].apply(pd.to_numeric, errors='coerce').isna().sum()

print(f"Non-numeric values in 'price': {non_numeric_price_0148}")
print(f"Non-numeric values in 'consumption': {non_numeric_consumption_0148}")
print(f"Non-numeric values in 'eprice': {non_numeric_eprice_0148}")

# 10.2 Setting the missing value in 'price' to the mean and converting to numeric
AmogVardhanKona['price'] = pd.to_numeric(AmogVardhanKona['price'], errors='coerce')
mean_price_0148 = AmogVardhanKona['price'].mean()
AmogVardhanKona['price'].fillna(mean_price_0148, inplace=True)

# Step 11: Compute Measures of Central Tendency and Dispersion for 'consumption' Column

# 11.1 Central Tendency: Mean, Median, Mode
mean_consumption_0148 = AmogVardhanKona['consumption'].mean()
median_consumption_0148 = AmogVardhanKona['consumption'].median()
mode_consumption_0148 = AmogVardhanKona['consumption'].mode()[0]

print(f"Mean of consumption: {mean_consumption_0148}")
print(f"Median of consumption: {median_consumption_0148}")
print(f"Mode of consumption: {mode_consumption_0148}")

# 11.2 Dispersion: Standard Deviation and Variance
sd_consumption_0148 = AmogVardhanKona['consumption'].std()
var_consumption_0148 = AmogVardhanKona['consumption'].var()

print(f"Standard Deviation of consumption: {sd_consumption_0148}")
print(f"Variance of consumption: {var_consumption_0148}")

# 11.3 Quartile Ranges and IQR
consumption_quantiles_0148 = AmogVardhanKona['consumption'].quantile([0.25, 0.5, 0.75])
iqr_consumption_0148 = consumption_quantiles_0148[0.75] - consumption_quantiles_0148[0.25]

print(f"Quartiles of consumption:\n{consumption_quantiles_0148}")
print(f"Interquartile Range (IQR) of consumption: {iqr_consumption_0148}")

# Step 12: Calculate Correlation Between Price and Consumption
cor_price_consumption = AmogVardhanKona[['price', 'consumption']].corr().iloc[0, 1]
print(f"Correlation between price and consumption: {cor_price_consumption}")

# Step 13: Univariate Analysis (Plots)

# 13.1 Distribution Plot: Histogram for consumption
plt.figure(figsize=(8, 6))
plt.hist(AmogVardhanKona['consumption'], bins=20, color='lightblue', edgecolor='black')
plt.title('21BDS0148 - Consumption Distribution Plot')
plt.xlabel('Consumption')
plt.ylabel('Frequency')
plt.show()

# Histogram for consumption using Seaborn
sns.histplot(AmogVardhanKona['consumption'], kde=False, bins=20, color='lightblue')
plt.title('21BDS0148 - Consumption Distribution Plot')
plt.xlabel('Consumption')
plt.ylabel('Frequency')
plt.show()

# 13.2 Distribution Plot Histogram for price
plt.figure(figsize=(8, 6))
plt.hist(AmogVardhanKona['price'], bins=20, color='lightgreen', edgecolor='black')
plt.title('21BDS0148 - Price Distribution Plot')
plt.xlabel('Price')
plt.ylabel('Frequency')
plt.show()

# Histogram for price using Seaborn
sns.histplot(AmogVardhanKona['price'], kde=False, bins=20, color='lightgreen')
plt.title('21BDS0148 - Price Distribution Plot')
plt.xlabel('Price')
plt.ylabel('Frequency')
plt.show()

# 13.3 Distribution Plot Density for price
plt.figure(figsize=(8, 6))
sns.kdeplot(AmogVardhanKona['price'], shade=True, color='purple')
plt.title('21BDS0148 - Price Density Plot')
plt.xlabel('Price')
plt.ylabel('Density')
plt.show()

# 13.4 Distribution Plot (Histogram + Density for price)
plt.figure(figsize=(8, 6))
sns.histplot(AmogVardhanKona['price'], kde=True, bins=20, color='lightgreen', line_kws={'color': 'purple'})
plt.title('21BDS0148 - Price Histogram and Density Plot')
plt.xlabel('Price')
plt.ylabel('Frequency/Density')
plt.show()

# 13.5 Boxplot for price
plt.figure(figsize=(8, 6))
sns.boxplot(x=AmogVardhanKona['price'], color='lightblue')
plt.title('21BDS0148 - Price Boxplot')
plt.xlabel('Price')
plt.show()

# 13.6 Display a Barplot for 'state' (Vertical and Horizontal)
# Vertical Barplot
plt.figure(figsize=(12, 6))
sns.countplot(x='state', data=AmogVardhanKona, palette='Blues')
plt.title('21BDS0148 - Barplot of States')
plt.xlabel('State')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()

# Horizontal Barplot
plt.figure(figsize=(8, 10))
sns.countplot(y='state', data=AmogVardhanKona, palette='Blues')
plt.title('21BDS0148 - Barplot of States')
plt.xlabel('Count')
plt.ylabel('State')
plt.show()

# 13.7 Display Pie Plot for State
state_counts = AmogVardhanKona['state'].value_counts()
plt.figure(figsize=(10, 8))
plt.pie(state_counts, labels=state_counts.index, autopct='%1.1f%%', startangle=90, colors=sns.color_palette('Set2'))
plt.title('21BDS0148 - Pie Chart for States')
plt.axis('equal')  # Equal aspect ratio ensures the pie is drawn as a circle.
plt.show()

# 13.8 Display Dot Plot for 'price'
plt.figure(figsize=(10, 6))
sns.stripplot(x=AmogVardhanKona['price'], color='purple', jitter=True, size=6)
plt.title('21BDS0148 - Dot Plot for Price')
plt.xlabel('Price')
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
AmogVardhanKona = pd.read_csv('eda_data_21BDS0148.csv')

# Step 1: Replace '?' with NaN (if applicable)
AmogVardhanKona.replace('?', np.nan, inplace=True)

# Step 2: Convert columns that should be numeric to numeric, coercing errors to NaN
numeric_columns = ['consumption', 'price', 'eprice', 'oprice', 'lprice', 'heating', 'income']
for col in numeric_columns:
    AmogVardhanKona[col] = pd.to_numeric(AmogVardhanKona[col], errors='coerce')

# Step 3: Handle missing values after conversion to numeric (impute missing values)
numeric_cols_0148 = AmogVardhanKona.select_dtypes(include=['float64', 'int64']).columns
AmogVardhanKona[numeric_cols_0148] = AmogVardhanKona[numeric_cols_0148].fillna(AmogVardhanKona[numeric_cols_0148].mean())

# Step 4: Handle missing values in non-numeric columns by using the mode (most frequent value)
non_numeric_cols_0148 = AmogVardhanKona.select_dtypes(exclude=['float64', 'int64']).columns
for col in non_numeric_cols_0148:
    AmogVardhanKona[col] = AmogVardhanKona[col].fillna(AmogVardhanKona[col].mode()[0])

# Step 5: Check for remaining missing values
print("Missing values after imputation:\n", AmogVardhanKona.isna().sum())

# Bivariate and Multivariate Analysis

# 1. Categorical vs Categorical: Stacked Bar Plot (state vs year)
plt.figure(figsize=(12, 6))
sns.countplot(data=AmogVardhanKona, x="state", hue='year', dodge=False, palette='Set2')
plt.title("21BDS0148 - Stacked Bar Plot: State vs Year")
plt.xlabel('State')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.legend(title='Year', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

# 2. Categorical vs Quantitative: Bar Plot (Price vs State)
plt.figure(figsize=(12, 6))
sns.barplot(data=AmogVardhanKona, x='state', y='price', palette='Set2')
plt.title("21BDS0148 - Bar Chart: Price vs State")
plt.xlabel('State')
plt.ylabel('Price')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# 3. Quantitative vs Quantitative: Scatter Plot (Price vs Consumption)
plt.figure(figsize=(10, 6))
sns.scatterplot(data=AmogVardhanKona, x='price', y='consumption', hue='state', palette='Set2')
plt.title("21BDS0148 - Scatter Plot: Price vs Consumption")
plt.xlabel('Price')
plt.ylabel('Consumption')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

# 4. Quantitative vs Quantitative: Heatmap (Correlation matrix)
numeric_data_0148 = AmogVardhanKona.select_dtypes(include=['number'])
corr_matrix_0148 = numeric_data_0148.corr()
plt.figure(figsize=(12, 10))
sns.heatmap(corr_matrix_0148, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)
plt.title("21BDS0148 - Heatmap of Correlation Matrix")
plt.tight_layout()
plt.show()

# 5. Categorical vs Quantitative: Density Plot (Price vs State)
plt.figure(figsize=(10, 6))
sns.kdeplot(data=AmogVardhanKona, x='price', hue='state', fill=True, palette='Set2')
plt.title("21BDS0148 - Density Plot: Price vs State")
plt.xlabel('Price')
plt.ylabel('Density')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

# 6. Categorical vs Quantitative: Box Plot (Price vs State)
plt.figure(figsize=(12, 6))
sns.boxplot(data=AmogVardhanKona, x='state', y='price', palette='Set2')
plt.title("21BDS0148 - Box Plot: Price vs State")
plt.xlabel('State')
plt.ylabel('Price')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()